Allows branches other than master to be pushed. Creates new websites with the branch name in the url. Closes #29.

diff --git a/bin/gitreceive b/bin/gitreceive
--- a/bin/gitreceive
+++ b/bin/gitreceive
@@ -66,15 +66,17 @@ EOF
     do
       # Only run this script for the master branch. You can remove this 
       # if block if you wish to run it for others as well.
-      if [[ $refname = "refs/heads/master" ]] ; then
- 
-        git archive $newrev | $GITHOME/receiver "$RECEIVE_REPO" "$newrev" "$RECEIVE_USER" "$RECEIVE_FINGERPRINT"  
- 
-        rc=$?
-        if [[ $rc != 0 ]] ; then
-          echo "      ERROR: failed on rev $newrev - push denied"
-          exit $rc
-        fi
+      if [[ $refname != "refs/heads/master" ]] ; then
+        BRANCH=$(echo $refname | cut -d '/' -f 3)
+        RECEIVE_REPO="$RECEIVE_REPO-$BRANCH"
+      fi
+      
+      git archive $newrev | $GITHOME/receiver "$RECEIVE_REPO" "$newrev" "$RECEIVE_USER" "$RECEIVE_FINGERPRINT"  
+
+      rc=$?
+      if [[ $rc != 0 ]] ; then
+        echo "      ERROR: failed on rev $newrev - push denied"
+        exit $rc
       fi
     done
     #exit 1 # for debugging
